bank: Account.cc Account_node.cc Bank_linked.cc Bank_vector.cc bank_main.cc
	g++ Account.cc Account_node.cc Bank_linked.cc Bank_vector.cc bank_main.cc -o bank -g -std=c++17

generator: randomNumberGenerator.cc
	g++ randomNumberGenerator.cc -o generator -g -std=c++17
